CREATE DATABASE IF NOT EXISTS sigace_db;
use sigace_db;

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS liceos (
  SIG VARCHAR(10) PRIMARY KEY,
  razon_social VARCHAR(50) NULL,
  nombre VARCHAR(50) NOT NULL,
  direccion VARCHAR(50) NOT NULL,
  telefono VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  tipo ENUM('pública', 'privada') NOT NULL,
  codigo_DEA VARCHAR(10) UNIQUE,
  rif VARCHAR(20) UNIQUE,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE liceos ADD CONSTRAINT chk_solo_uno CHECK(
  (codigo_DEA IS NULL AND rif IS NOT NULL) OR (codigo_DEA IS NOT NULL AND rif IS NULL) OR (tipo = 'pública' AND razon_social IS NOT NULL) OR (tipo = 'privada' AND razon_social IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cedula VARCHAR(10) NOT NULL UNIQUE,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  numero_de_telefono VARCHAR(50) NOT NULL UNIQUE,
  contraseña VARCHAR(255) NOT NULL,
  rol_id INT NOT NULL,
  SIG VARCHAR(10) NOT NULL,

  FOREIGN KEY (rol_id) REFERENCES roles(id),
  FOREIGN KEY (SIG) REFERENCES liceos(SIG)
);